### ISSUE TITLE
Incorrect CURIE

### ISSUE THREAD

**Issue by dkoslicki** [NCATSTranslator/Tests#63]
Test 18, asset 334, dupilumab has a non-standard CURIE and I think it should be UNII:420K487FSG instead.

**Comment by maximusunc** [comment]
PR opened: https://github.com/NCATSTranslator/Tests/pull/67

**Comment by maximusunc** [comment]
Fixed.

**Comment by colleenXu** [comment]
Adding a note! I agree with the update to [UNII:420K487FSG](https://nodenormalization-sri.renci.org/get_normalized_nodes?curie=UNII:420K487FSG&conflate=true&drug_chemical_conflate=true&description=false)

The old answer ID [PUBCHEM.COMPOUND:223365910 doesn't resolve in NodeNorm](https://nodenormalization-sri.renci.org/get_normalized_nodes?curie=PUBCHEM.COMPOUND:223365910&conflate=true&drug_chemical_conflate=true&description=false)
